CC = g++
EXEC = portugol
OBJS = string_utils.cpp Automato.cpp
FLAGS = -g -o

all:
	$(CC) $(OBJS) $(EXEC).cpp $(FLAGS) $(EXEC)

$(EXEC):
	$(CC) $(OBJS) $(EXEC).cpp $(FLAGS) $(EXEC)

clear:
	rm $(EXEC)
