### makefile ###

EXEC = l5e2
OBJS = string_utils.cpp Automato.cpp
FLAGS = -g -o

all:
	g++ $(OBJS) $(EXEC).cpp $(FLAGS) $(EXEC)

$(EXEC):
	g++ $(OBJS) $(EXEC).cpp $(FLAGS) $(EXEC)

clear:
	rm $(EXEC)
